name: Generate css vars from tokens and copied
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer input/design-tokens.json input/base.json base
      - run: npx token-transformer input/design-tokens.json input/brand-a.json base,brand-a base --expandTypography=true
      - run: npx token-transformer input/design-tokens.json input/brand-b.json base,brand-b base --expandTypography=true
      - run: node build.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build tokens
  copy_tokens:
    runs-on: ubuntu-22.04
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          src_branch: main
          src_path: output/.
          dst_owner: ernishant83
          dst_repo_name: stencil-storybook-css
          dst_branch: main
          dst_path: src/css/.
          username: ernishant83
          email: ernishant83@gmail.com
          commit_message: copy css tokens
